spring:
    application:
        name: ip-service
eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka-server:8761/eureka/
#            defaultZone: http://localhost:8761/eureka/
