spring:
  application:
    name: my-eureka-server

server:
    port: ${PORT:8761}

eureka:
    client:
        registerWithEureka: false
        fetchRegistry: false
        server:
            waitTimeInMsWhenSyncEmpty: 0